### ISSUE TITLE
ROOT latest version compilation fail

### ISSUE THREAD

**Issue by suvorov21** [nadrino/cpp-generic-toolbox#1]
There is a problem with the latest version of ROOT. 
The example compiles and works perfectly with ROOT v6-20-06, but with the latest v6-24-02 it returns an error during compilation
```
[ 50%] Building CXX object CMakeFiles/GenericToolboxExample.dir/example/main.cpp.o
In file included from ***/cpp-generic-toolbox/example/main.cpp:12:
In file included from ***/cpp-generic-toolbox/./include/GenericToolbox.Root.h:82:
***/cpp-generic-toolbox/./include/implementation/GenericToolbox.Root.impl.h:288:11: error: variable 'cwd' with type 'auto *' has incompatible initializer of type 'ROOT::Internal::TDirectoryAtomicAdapter'
    auto* cwd = gDirectory;
          ^     ~~~~~~~~~~
1 error generated.
```
That happens for me on Mac with clang-1205.0.22.11
Observed both on master and v2.1.0

**Comment by nadrino** [comment]
Hey ;)

Thanks for the repport!
I'm gonna see what happen with the new version of ROOT. In fact I would have expected gDirectory to be a pointer, but it seems it's not the case...

Keep you informed :)

**Comment by nadrino** [comment]
Fixed: https://github.com/nadrino/cpp-generic-toolbox/commit/19d5d5fb9135d18309a0ef42a2714b89022fd3bc

Cheers ;)
